### ISSUE TITLE
Add SearchBar

### ISSUE THREAD

**Issue by Potential17** [Potential17/Hacktoberfest-2020#88]
A search bar with auto complete options and quickly displays the matching result of Hactoberfest participants listed on the site.

**Comment by udayax** [comment]
is this issue is still open. I would like to contribute search bar .

**Comment by Potential17** [comment]
Yes

**Comment by udayax** [comment]
OK Thanks

**Comment by udayax** [comment]
Added search bar and made pull request @Potential17  Waiting for your replay

**Comment by udayax** [comment]
Thanks ... @Potential17
